const countries = [
    "Vietnam",
    "United States",
    "Canada",
    "Australia",
    "Japan",
    "Germany",
    "Brazil",
    "South Africa",
    "France",
    "India",
    "Italy",
    "China",
    "Mexico",
    "United Kingdom",
    "Russia",
    "South Korea",
    "Argentina",
    "Egypt",
    "Saudi Arabia",
    "New Zealand",
    "Spain",
    "Turkey",
    "Thailand",
    "Indonesia",
    "Sweden",
    "Switzerland",
    "Norway",
    "Greece",
    "Netherlands",
    "Portugal",
    "Nigeria",
];

export { countries };
